
namespace PurchaseDesktop.Formularios
{
    partial class FDetails
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FDetails));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties57 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties58 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties59 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties60 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties61 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties62 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties63 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties64 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties65 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties66 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties67 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties68 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties69 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties70 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties71 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties72 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.PanelHeader = new System.Windows.Forms.Panel();
            this.LabelPanel = new System.Windows.Forms.Label();
            this.BtnCerrar = new Bunifu.UI.WinForms.BunifuImageButton();
            this.FDock = new Bunifu.UI.WinForms.BunifuFormDock();
            this.Grid = new TenTec.Windows.iGridLib.iGrid();
            this.TxtPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtDescription = new Bunifu.UI.WinForms.BunifuTextBox();
            this.CboAccount = new System.Windows.Forms.ComboBox();
            this.TxtQty = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.BtnNewDetail = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuSeparator2 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.CboMedidas = new System.Windows.Forms.ComboBox();
            this.PanelFooter = new System.Windows.Forms.Panel();
            this.TxtTotal = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtTax = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtNet = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtExent = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtGlosa = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ChkExent = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.PanelHeader.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.Grid)).BeginInit();
            this.PanelFooter.SuspendLayout();
            this.SuspendLayout();
            // 
            // PanelHeader
            // 
            this.PanelHeader.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(48)))));
            this.PanelHeader.Controls.Add(this.LabelPanel);
            this.PanelHeader.Controls.Add(this.BtnCerrar);
            this.PanelHeader.Dock = System.Windows.Forms.DockStyle.Top;
            this.PanelHeader.Location = new System.Drawing.Point(0, 0);
            this.PanelHeader.Name = "PanelHeader";
            this.PanelHeader.Size = new System.Drawing.Size(546, 25);
            this.PanelHeader.TabIndex = 1;
            // 
            // LabelPanel
            // 
            this.LabelPanel.Dock = System.Windows.Forms.DockStyle.Left;
            this.LabelPanel.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LabelPanel.ForeColor = System.Drawing.Color.White;
            this.LabelPanel.Location = new System.Drawing.Point(0, 0);
            this.LabelPanel.Name = "LabelPanel";
            this.LabelPanel.Size = new System.Drawing.Size(181, 25);
            this.LabelPanel.TabIndex = 28;
            this.LabelPanel.Text = "Details of Products/Services";
            this.LabelPanel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // BtnCerrar
            // 
            this.BtnCerrar.ActiveImage = ((System.Drawing.Image)(resources.GetObject("BtnCerrar.ActiveImage")));
            this.BtnCerrar.AllowAnimations = true;
            this.BtnCerrar.AllowBuffering = false;
            this.BtnCerrar.AllowToggling = false;
            this.BtnCerrar.AllowZooming = true;
            this.BtnCerrar.AllowZoomingOnFocus = false;
            this.BtnCerrar.BackColor = System.Drawing.Color.Transparent;
            this.BtnCerrar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCerrar.ErrorImage = ((System.Drawing.Image)(resources.GetObject("BtnCerrar.ErrorImage")));
            this.BtnCerrar.FadeWhenInactive = false;
            this.BtnCerrar.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.BtnCerrar.Image = ((System.Drawing.Image)(resources.GetObject("BtnCerrar.Image")));
            this.BtnCerrar.ImageActive = ((System.Drawing.Image)(resources.GetObject("BtnCerrar.ImageActive")));
            this.BtnCerrar.ImageLocation = null;
            this.BtnCerrar.ImageMargin = 5;
            this.BtnCerrar.ImageSize = new System.Drawing.Size(17, 17);
            this.BtnCerrar.ImageZoomSize = new System.Drawing.Size(22, 22);
            this.BtnCerrar.InitialImage = ((System.Drawing.Image)(resources.GetObject("BtnCerrar.InitialImage")));
            this.BtnCerrar.Location = new System.Drawing.Point(521, 1);
            this.BtnCerrar.Name = "BtnCerrar";
            this.BtnCerrar.Rotation = 0;
            this.BtnCerrar.ShowActiveImage = true;
            this.BtnCerrar.ShowCursorChanges = true;
            this.BtnCerrar.ShowImageBorders = true;
            this.BtnCerrar.ShowSizeMarkers = false;
            this.BtnCerrar.Size = new System.Drawing.Size(22, 22);
            this.BtnCerrar.TabIndex = 27;
            this.BtnCerrar.TabStop = false;
            this.BtnCerrar.ToolTipText = "";
            this.BtnCerrar.WaitOnLoad = false;
            this.BtnCerrar.Zoom = 5;
            this.BtnCerrar.ZoomSpeed = 10;
            this.BtnCerrar.Click += new System.EventHandler(this.BtnCerrar_Click);
            // 
            // FDock
            // 
            this.FDock.AllowFormDragging = true;
            this.FDock.AllowFormDropShadow = true;
            this.FDock.AllowFormResizing = true;
            this.FDock.AllowHidingBottomRegion = true;
            this.FDock.AllowOpacityChangesWhileDragging = true;
            this.FDock.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.FDock.BorderOptions.BottomBorder.BorderThickness = 1;
            this.FDock.BorderOptions.BottomBorder.ShowBorder = true;
            this.FDock.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.FDock.BorderOptions.LeftBorder.BorderThickness = 1;
            this.FDock.BorderOptions.LeftBorder.ShowBorder = true;
            this.FDock.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.FDock.BorderOptions.RightBorder.BorderThickness = 1;
            this.FDock.BorderOptions.RightBorder.ShowBorder = true;
            this.FDock.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.FDock.BorderOptions.TopBorder.BorderThickness = 1;
            this.FDock.BorderOptions.TopBorder.ShowBorder = true;
            this.FDock.ContainerControl = this;
            this.FDock.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(48)))));
            this.FDock.DockingIndicatorsOpacity = 0.5D;
            this.FDock.DockingOptions.DockAll = true;
            this.FDock.DockingOptions.DockBottomLeft = true;
            this.FDock.DockingOptions.DockBottomRight = true;
            this.FDock.DockingOptions.DockFullScreen = true;
            this.FDock.DockingOptions.DockLeft = true;
            this.FDock.DockingOptions.DockRight = true;
            this.FDock.DockingOptions.DockTopLeft = true;
            this.FDock.DockingOptions.DockTopRight = true;
            this.FDock.FormDraggingOpacity = 0.9D;
            this.FDock.ParentForm = this;
            this.FDock.ShowCursorChanges = true;
            this.FDock.ShowDockingIndicators = true;
            this.FDock.TitleBarOptions.AllowFormDragging = true;
            this.FDock.TitleBarOptions.BunifuFormDock = this.FDock;
            this.FDock.TitleBarOptions.DoubleClickToExpandWindow = false;
            this.FDock.TitleBarOptions.TitleBarControl = this.PanelHeader;
            this.FDock.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // Grid
            // 
            this.Grid.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.Grid.Header.Height = 16;
            this.Grid.Location = new System.Drawing.Point(0, 161);
            this.Grid.Name = "Grid";
            this.Grid.Size = new System.Drawing.Size(546, 161);
            this.Grid.TabIndex = 18;
            this.Grid.ColDividerDoubleClick += new TenTec.Windows.iGridLib.iGColDividerDoubleClickEventHandler(this.Grid_ColDividerDoubleClick);
            this.Grid.RequestCellToolTipText += new TenTec.Windows.iGridLib.iGRequestCellToolTipTextEventHandler(this.Grid_RequestCellToolTipText);
            // 
            // TxtPrice
            // 
            this.TxtPrice.AcceptsReturn = false;
            this.TxtPrice.AcceptsTab = false;
            this.TxtPrice.AnimationSpeed = 200;
            this.TxtPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtPrice.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            this.TxtPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtPrice.BackgroundImage")));
            this.TxtPrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtPrice.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtPrice.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtPrice.BorderRadius = 1;
            this.TxtPrice.BorderThickness = 1;
            this.TxtPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPrice.DefaultFont = new System.Drawing.Font("Tahoma", 9.75F);
            this.TxtPrice.DefaultText = "";
            this.TxtPrice.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            this.TxtPrice.HideSelection = true;
            this.TxtPrice.IconLeft = null;
            this.TxtPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPrice.IconPadding = 10;
            this.TxtPrice.IconRight = null;
            this.TxtPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPrice.Lines = new string[0];
            this.TxtPrice.Location = new System.Drawing.Point(333, 95);
            this.TxtPrice.MaxLength = 9;
            this.TxtPrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtPrice.Modified = false;
            this.TxtPrice.Multiline = false;
            this.TxtPrice.Name = "TxtPrice";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtPrice.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtPrice.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtPrice.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtPrice.OnIdleState = stateProperties44;
            this.TxtPrice.Padding = new System.Windows.Forms.Padding(3);
            this.TxtPrice.PasswordChar = '\0';
            this.TxtPrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtPrice.PlaceholderText = "$ Price";
            this.TxtPrice.ReadOnly = false;
            this.TxtPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtPrice.SelectedText = "";
            this.TxtPrice.SelectionLength = 0;
            this.TxtPrice.SelectionStart = 0;
            this.TxtPrice.ShortcutsEnabled = true;
            this.TxtPrice.Size = new System.Drawing.Size(93, 25);
            this.TxtPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtPrice.TabIndex = 24;
            this.TxtPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtPrice.TextMarginBottom = 0;
            this.TxtPrice.TextMarginLeft = 1;
            this.TxtPrice.TextMarginTop = 0;
            this.TxtPrice.TextPlaceholder = "$ Price";
            this.TxtPrice.UseSystemPasswordChar = false;
            this.TxtPrice.WordWrap = true;
            this.TxtPrice.TextChange += new System.EventHandler(this.TxtPrice_TextChange);
            // 
            // TxtDescription
            // 
            this.TxtDescription.AcceptsReturn = false;
            this.TxtDescription.AcceptsTab = false;
            this.TxtDescription.AnimationSpeed = 200;
            this.TxtDescription.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtDescription.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtDescription.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            this.TxtDescription.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtDescription.BackgroundImage")));
            this.TxtDescription.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtDescription.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtDescription.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtDescription.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtDescription.BorderRadius = 1;
            this.TxtDescription.BorderThickness = 1;
            this.TxtDescription.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtDescription.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtDescription.DefaultFont = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TxtDescription.DefaultText = "";
            this.TxtDescription.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            this.TxtDescription.HideSelection = true;
            this.TxtDescription.IconLeft = null;
            this.TxtDescription.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtDescription.IconPadding = 10;
            this.TxtDescription.IconRight = null;
            this.TxtDescription.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtDescription.Lines = new string[0];
            this.TxtDescription.Location = new System.Drawing.Point(9, 62);
            this.TxtDescription.MaxLength = 100;
            this.TxtDescription.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtDescription.Modified = false;
            this.TxtDescription.Multiline = false;
            this.TxtDescription.Name = "TxtDescription";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtDescription.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtDescription.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtDescription.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtDescription.OnIdleState = stateProperties48;
            this.TxtDescription.Padding = new System.Windows.Forms.Padding(3);
            this.TxtDescription.PasswordChar = '\0';
            this.TxtDescription.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtDescription.PlaceholderText = "Enter Description Product";
            this.TxtDescription.ReadOnly = false;
            this.TxtDescription.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtDescription.SelectedText = "";
            this.TxtDescription.SelectionLength = 0;
            this.TxtDescription.SelectionStart = 0;
            this.TxtDescription.ShortcutsEnabled = true;
            this.TxtDescription.Size = new System.Drawing.Size(452, 25);
            this.TxtDescription.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtDescription.TabIndex = 22;
            this.TxtDescription.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtDescription.TextMarginBottom = 0;
            this.TxtDescription.TextMarginLeft = 1;
            this.TxtDescription.TextMarginTop = 0;
            this.TxtDescription.TextPlaceholder = "Enter Description Product";
            this.TxtDescription.UseSystemPasswordChar = false;
            this.TxtDescription.WordWrap = true;
            // 
            // CboAccount
            // 
            this.CboAccount.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Suggest;
            this.CboAccount.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
            this.CboAccount.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.CboAccount.Font = new System.Drawing.Font("Tahoma", 9.75F);
            this.CboAccount.FormattingEnabled = true;
            this.CboAccount.Location = new System.Drawing.Point(9, 95);
            this.CboAccount.Name = "CboAccount";
            this.CboAccount.Size = new System.Drawing.Size(273, 24);
            this.CboAccount.TabIndex = 23;
            // 
            // TxtQty
            // 
            this.TxtQty.AcceptsReturn = false;
            this.TxtQty.AcceptsTab = false;
            this.TxtQty.AnimationSpeed = 200;
            this.TxtQty.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtQty.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtQty.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            this.TxtQty.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtQty.BackgroundImage")));
            this.TxtQty.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtQty.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtQty.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtQty.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtQty.BorderRadius = 1;
            this.TxtQty.BorderThickness = 1;
            this.TxtQty.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtQty.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtQty.DefaultFont = new System.Drawing.Font("Tahoma", 9.75F);
            this.TxtQty.DefaultText = "";
            this.TxtQty.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            this.TxtQty.HideSelection = true;
            this.TxtQty.IconLeft = null;
            this.TxtQty.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtQty.IconPadding = 10;
            this.TxtQty.IconRight = null;
            this.TxtQty.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtQty.Lines = new string[0];
            this.TxtQty.Location = new System.Drawing.Point(9, 31);
            this.TxtQty.MaxLength = 7;
            this.TxtQty.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtQty.Modified = false;
            this.TxtQty.Multiline = false;
            this.TxtQty.Name = "TxtQty";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtQty.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtQty.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtQty.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtQty.OnIdleState = stateProperties52;
            this.TxtQty.Padding = new System.Windows.Forms.Padding(3);
            this.TxtQty.PasswordChar = '\0';
            this.TxtQty.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtQty.PlaceholderText = "Qty";
            this.TxtQty.ReadOnly = false;
            this.TxtQty.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtQty.SelectedText = "";
            this.TxtQty.SelectionLength = 0;
            this.TxtQty.SelectionStart = 0;
            this.TxtQty.ShortcutsEnabled = true;
            this.TxtQty.Size = new System.Drawing.Size(66, 25);
            this.TxtQty.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtQty.TabIndex = 20;
            this.TxtQty.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtQty.TextMarginBottom = 0;
            this.TxtQty.TextMarginLeft = 1;
            this.TxtQty.TextMarginTop = 0;
            this.TxtQty.TextPlaceholder = "Qty";
            this.TxtQty.UseSystemPasswordChar = false;
            this.TxtQty.WordWrap = true;
            this.TxtQty.TextChange += new System.EventHandler(this.TxtQty_TextChange);
            // 
            // TxtName
            // 
            this.TxtName.AcceptsReturn = false;
            this.TxtName.AcceptsTab = false;
            this.TxtName.AnimationSpeed = 200;
            this.TxtName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtName.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            this.TxtName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtName.BackgroundImage")));
            this.TxtName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtName.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtName.BorderRadius = 1;
            this.TxtName.BorderThickness = 1;
            this.TxtName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtName.DefaultFont = new System.Drawing.Font("Tahoma", 9.75F);
            this.TxtName.DefaultText = "";
            this.TxtName.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            this.TxtName.HideSelection = true;
            this.TxtName.IconLeft = null;
            this.TxtName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtName.IconPadding = 10;
            this.TxtName.IconRight = null;
            this.TxtName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtName.Lines = new string[0];
            this.TxtName.Location = new System.Drawing.Point(164, 31);
            this.TxtName.MaxLength = 100;
            this.TxtName.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtName.Modified = false;
            this.TxtName.Multiline = false;
            this.TxtName.Name = "TxtName";
            stateProperties53.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtName.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtName.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtName.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Silver;
            stateProperties56.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtName.OnIdleState = stateProperties56;
            this.TxtName.Padding = new System.Windows.Forms.Padding(3);
            this.TxtName.PasswordChar = '\0';
            this.TxtName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtName.PlaceholderText = "Enter Product Name";
            this.TxtName.ReadOnly = false;
            this.TxtName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtName.SelectedText = "";
            this.TxtName.SelectionLength = 0;
            this.TxtName.SelectionStart = 0;
            this.TxtName.ShortcutsEnabled = true;
            this.TxtName.Size = new System.Drawing.Size(370, 25);
            this.TxtName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtName.TabIndex = 21;
            this.TxtName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtName.TextMarginBottom = 0;
            this.TxtName.TextMarginLeft = 1;
            this.TxtName.TextMarginTop = 0;
            this.TxtName.TextPlaceholder = "Enter Product Name";
            this.TxtName.UseSystemPasswordChar = false;
            this.TxtName.WordWrap = true;
            // 
            // bunifuSeparator1
            // 
            this.bunifuSeparator1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(37)))), ((int)(((byte)(38)))));
            this.bunifuSeparator1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator1.BackgroundImage")));
            this.bunifuSeparator1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.bunifuSeparator1.LineColor = System.Drawing.Color.FromArgb(((int)(((byte)(154)))), ((int)(((byte)(196)))), ((int)(((byte)(85)))));
            this.bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator1.LineThickness = 1;
            this.bunifuSeparator1.Location = new System.Drawing.Point(0, 353);
            this.bunifuSeparator1.Name = "bunifuSeparator1";
            this.bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator1.Size = new System.Drawing.Size(546, 1);
            this.bunifuSeparator1.TabIndex = 25;
            // 
            // BtnNewDetail
            // 
            this.BtnNewDetail.ActiveImage = ((System.Drawing.Image)(resources.GetObject("BtnNewDetail.ActiveImage")));
            this.BtnNewDetail.AllowAnimations = true;
            this.BtnNewDetail.AllowBuffering = false;
            this.BtnNewDetail.AllowToggling = false;
            this.BtnNewDetail.AllowZooming = true;
            this.BtnNewDetail.AllowZoomingOnFocus = false;
            this.BtnNewDetail.BackColor = System.Drawing.Color.Transparent;
            this.BtnNewDetail.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnNewDetail.ErrorImage = ((System.Drawing.Image)(resources.GetObject("BtnNewDetail.ErrorImage")));
            this.BtnNewDetail.FadeWhenInactive = false;
            this.BtnNewDetail.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.BtnNewDetail.Image = ((System.Drawing.Image)(resources.GetObject("BtnNewDetail.Image")));
            this.BtnNewDetail.ImageActive = ((System.Drawing.Image)(resources.GetObject("BtnNewDetail.ImageActive")));
            this.BtnNewDetail.ImageLocation = null;
            this.BtnNewDetail.ImageMargin = 20;
            this.BtnNewDetail.ImageSize = new System.Drawing.Size(35, 35);
            this.BtnNewDetail.ImageZoomSize = new System.Drawing.Size(55, 55);
            this.BtnNewDetail.InitialImage = ((System.Drawing.Image)(resources.GetObject("BtnNewDetail.InitialImage")));
            this.BtnNewDetail.Location = new System.Drawing.Point(479, 63);
            this.BtnNewDetail.Name = "BtnNewDetail";
            this.BtnNewDetail.Rotation = 0;
            this.BtnNewDetail.ShowActiveImage = true;
            this.BtnNewDetail.ShowCursorChanges = true;
            this.BtnNewDetail.ShowImageBorders = true;
            this.BtnNewDetail.ShowSizeMarkers = false;
            this.BtnNewDetail.Size = new System.Drawing.Size(55, 55);
            this.BtnNewDetail.TabIndex = 26;
            this.BtnNewDetail.TabStop = false;
            this.BtnNewDetail.ToolTipText = "";
            this.BtnNewDetail.WaitOnLoad = false;
            this.BtnNewDetail.Zoom = 20;
            this.BtnNewDetail.ZoomSpeed = 10;
            this.BtnNewDetail.Click += new System.EventHandler(this.BtnNewDetail_Click);
            // 
            // bunifuSeparator2
            // 
            this.bunifuSeparator2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(37)))), ((int)(((byte)(38)))));
            this.bunifuSeparator2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator2.BackgroundImage")));
            this.bunifuSeparator2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator2.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator2.LineColor = System.Drawing.Color.FromArgb(((int)(((byte)(154)))), ((int)(((byte)(196)))), ((int)(((byte)(85)))));
            this.bunifuSeparator2.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator2.LineThickness = 1;
            this.bunifuSeparator2.Location = new System.Drawing.Point(0, 0);
            this.bunifuSeparator2.Name = "bunifuSeparator2";
            this.bunifuSeparator2.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator2.Size = new System.Drawing.Size(546, 1);
            this.bunifuSeparator2.TabIndex = 28;
            // 
            // CboMedidas
            // 
            this.CboMedidas.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Suggest;
            this.CboMedidas.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
            this.CboMedidas.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.CboMedidas.Font = new System.Drawing.Font("Tahoma", 9.75F);
            this.CboMedidas.FormattingEnabled = true;
            this.CboMedidas.Location = new System.Drawing.Point(81, 32);
            this.CboMedidas.Name = "CboMedidas";
            this.CboMedidas.Size = new System.Drawing.Size(77, 24);
            this.CboMedidas.TabIndex = 29;
            // 
            // PanelFooter
            // 
            this.PanelFooter.Controls.Add(this.TxtTotal);
            this.PanelFooter.Controls.Add(this.TxtTax);
            this.PanelFooter.Controls.Add(this.TxtNet);
            this.PanelFooter.Controls.Add(this.TxtExent);
            this.PanelFooter.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.PanelFooter.Location = new System.Drawing.Point(0, 322);
            this.PanelFooter.Name = "PanelFooter";
            this.PanelFooter.Size = new System.Drawing.Size(546, 31);
            this.PanelFooter.TabIndex = 30;
            // 
            // TxtTotal
            // 
            this.TxtTotal.AcceptsReturn = false;
            this.TxtTotal.AcceptsTab = false;
            this.TxtTotal.AnimationSpeed = 200;
            this.TxtTotal.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtTotal.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtTotal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            this.TxtTotal.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtTotal.BackgroundImage")));
            this.TxtTotal.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtTotal.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtTotal.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtTotal.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtTotal.BorderRadius = 1;
            this.TxtTotal.BorderThickness = 1;
            this.TxtTotal.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtTotal.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtTotal.DefaultFont = new System.Drawing.Font("Tahoma", 9.75F);
            this.TxtTotal.DefaultText = "";
            this.TxtTotal.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            this.TxtTotal.HideSelection = true;
            this.TxtTotal.IconLeft = null;
            this.TxtTotal.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtTotal.IconPadding = 12;
            this.TxtTotal.IconRight = null;
            this.TxtTotal.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtTotal.Lines = new string[0];
            this.TxtTotal.Location = new System.Drawing.Point(396, 3);
            this.TxtTotal.MaxLength = 15;
            this.TxtTotal.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtTotal.Modified = false;
            this.TxtTotal.Multiline = false;
            this.TxtTotal.Name = "TxtTotal";
            stateProperties57.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties57.FillColor = System.Drawing.Color.Empty;
            stateProperties57.ForeColor = System.Drawing.Color.Empty;
            stateProperties57.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtTotal.OnActiveState = stateProperties57;
            stateProperties58.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties58.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties58.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties58.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtTotal.OnDisabledState = stateProperties58;
            stateProperties59.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties59.FillColor = System.Drawing.Color.Empty;
            stateProperties59.ForeColor = System.Drawing.Color.Empty;
            stateProperties59.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtTotal.OnHoverState = stateProperties59;
            stateProperties60.BorderColor = System.Drawing.Color.Silver;
            stateProperties60.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            stateProperties60.ForeColor = System.Drawing.Color.Empty;
            stateProperties60.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtTotal.OnIdleState = stateProperties60;
            this.TxtTotal.Padding = new System.Windows.Forms.Padding(3);
            this.TxtTotal.PasswordChar = '\0';
            this.TxtTotal.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtTotal.PlaceholderText = "$ Total";
            this.TxtTotal.ReadOnly = true;
            this.TxtTotal.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtTotal.SelectedText = "";
            this.TxtTotal.SelectionLength = 0;
            this.TxtTotal.SelectionStart = 0;
            this.TxtTotal.ShortcutsEnabled = true;
            this.TxtTotal.Size = new System.Drawing.Size(126, 25);
            this.TxtTotal.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtTotal.TabIndex = 31;
            this.TxtTotal.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtTotal.TextMarginBottom = 0;
            this.TxtTotal.TextMarginLeft = 1;
            this.TxtTotal.TextMarginTop = 0;
            this.TxtTotal.TextPlaceholder = "$ Total";
            this.TxtTotal.UseSystemPasswordChar = false;
            this.TxtTotal.WordWrap = true;
            // 
            // TxtTax
            // 
            this.TxtTax.AcceptsReturn = false;
            this.TxtTax.AcceptsTab = false;
            this.TxtTax.AnimationSpeed = 200;
            this.TxtTax.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtTax.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtTax.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            this.TxtTax.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtTax.BackgroundImage")));
            this.TxtTax.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtTax.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtTax.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtTax.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtTax.BorderRadius = 1;
            this.TxtTax.BorderThickness = 1;
            this.TxtTax.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtTax.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtTax.DefaultFont = new System.Drawing.Font("Tahoma", 9.75F);
            this.TxtTax.DefaultText = "";
            this.TxtTax.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            this.TxtTax.HideSelection = true;
            this.TxtTax.IconLeft = null;
            this.TxtTax.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtTax.IconPadding = 10;
            this.TxtTax.IconRight = null;
            this.TxtTax.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtTax.Lines = new string[0];
            this.TxtTax.Location = new System.Drawing.Point(280, 3);
            this.TxtTax.MaxLength = 9;
            this.TxtTax.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtTax.Modified = false;
            this.TxtTax.Multiline = false;
            this.TxtTax.Name = "TxtTax";
            stateProperties61.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties61.FillColor = System.Drawing.Color.Empty;
            stateProperties61.ForeColor = System.Drawing.Color.Empty;
            stateProperties61.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtTax.OnActiveState = stateProperties61;
            stateProperties62.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties62.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties62.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties62.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtTax.OnDisabledState = stateProperties62;
            stateProperties63.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties63.FillColor = System.Drawing.Color.Empty;
            stateProperties63.ForeColor = System.Drawing.Color.Empty;
            stateProperties63.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtTax.OnHoverState = stateProperties63;
            stateProperties64.BorderColor = System.Drawing.Color.Silver;
            stateProperties64.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            stateProperties64.ForeColor = System.Drawing.Color.Empty;
            stateProperties64.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtTax.OnIdleState = stateProperties64;
            this.TxtTax.Padding = new System.Windows.Forms.Padding(3);
            this.TxtTax.PasswordChar = '\0';
            this.TxtTax.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtTax.PlaceholderText = "$ Tax";
            this.TxtTax.ReadOnly = true;
            this.TxtTax.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtTax.SelectedText = "";
            this.TxtTax.SelectionLength = 0;
            this.TxtTax.SelectionStart = 0;
            this.TxtTax.ShortcutsEnabled = true;
            this.TxtTax.Size = new System.Drawing.Size(103, 25);
            this.TxtTax.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtTax.TabIndex = 30;
            this.TxtTax.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtTax.TextMarginBottom = 0;
            this.TxtTax.TextMarginLeft = 1;
            this.TxtTax.TextMarginTop = 0;
            this.TxtTax.TextPlaceholder = "$ Tax";
            this.TxtTax.UseSystemPasswordChar = false;
            this.TxtTax.WordWrap = true;
            // 
            // TxtNet
            // 
            this.TxtNet.AcceptsReturn = false;
            this.TxtNet.AcceptsTab = false;
            this.TxtNet.AnimationSpeed = 200;
            this.TxtNet.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtNet.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtNet.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            this.TxtNet.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtNet.BackgroundImage")));
            this.TxtNet.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtNet.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtNet.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtNet.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtNet.BorderRadius = 1;
            this.TxtNet.BorderThickness = 1;
            this.TxtNet.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtNet.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNet.DefaultFont = new System.Drawing.Font("Tahoma", 9.75F);
            this.TxtNet.DefaultText = "";
            this.TxtNet.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            this.TxtNet.HideSelection = true;
            this.TxtNet.IconLeft = null;
            this.TxtNet.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNet.IconPadding = 12;
            this.TxtNet.IconRight = null;
            this.TxtNet.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNet.Lines = new string[0];
            this.TxtNet.Location = new System.Drawing.Point(48, 3);
            this.TxtNet.MaxLength = 9;
            this.TxtNet.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtNet.Modified = false;
            this.TxtNet.Multiline = false;
            this.TxtNet.Name = "TxtNet";
            stateProperties65.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties65.FillColor = System.Drawing.Color.Empty;
            stateProperties65.ForeColor = System.Drawing.Color.Empty;
            stateProperties65.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNet.OnActiveState = stateProperties65;
            stateProperties66.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties66.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties66.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties66.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtNet.OnDisabledState = stateProperties66;
            stateProperties67.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties67.FillColor = System.Drawing.Color.Empty;
            stateProperties67.ForeColor = System.Drawing.Color.Empty;
            stateProperties67.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNet.OnHoverState = stateProperties67;
            stateProperties68.BorderColor = System.Drawing.Color.Silver;
            stateProperties68.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            stateProperties68.ForeColor = System.Drawing.Color.Empty;
            stateProperties68.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNet.OnIdleState = stateProperties68;
            this.TxtNet.Padding = new System.Windows.Forms.Padding(3);
            this.TxtNet.PasswordChar = '\0';
            this.TxtNet.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtNet.PlaceholderText = "$ Net";
            this.TxtNet.ReadOnly = true;
            this.TxtNet.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtNet.SelectedText = "";
            this.TxtNet.SelectionLength = 0;
            this.TxtNet.SelectionStart = 0;
            this.TxtNet.ShortcutsEnabled = true;
            this.TxtNet.Size = new System.Drawing.Size(103, 25);
            this.TxtNet.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtNet.TabIndex = 29;
            this.TxtNet.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtNet.TextMarginBottom = 0;
            this.TxtNet.TextMarginLeft = 1;
            this.TxtNet.TextMarginTop = 0;
            this.TxtNet.TextPlaceholder = "$ Net";
            this.TxtNet.UseSystemPasswordChar = false;
            this.TxtNet.WordWrap = true;
            // 
            // TxtExent
            // 
            this.TxtExent.AcceptsReturn = false;
            this.TxtExent.AcceptsTab = false;
            this.TxtExent.AnimationSpeed = 200;
            this.TxtExent.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtExent.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtExent.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            this.TxtExent.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtExent.BackgroundImage")));
            this.TxtExent.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtExent.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtExent.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtExent.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtExent.BorderRadius = 1;
            this.TxtExent.BorderThickness = 1;
            this.TxtExent.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtExent.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtExent.DefaultFont = new System.Drawing.Font("Tahoma", 9.75F);
            this.TxtExent.DefaultText = "";
            this.TxtExent.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            this.TxtExent.HideSelection = true;
            this.TxtExent.IconLeft = null;
            this.TxtExent.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtExent.IconPadding = 12;
            this.TxtExent.IconRight = null;
            this.TxtExent.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtExent.Lines = new string[0];
            this.TxtExent.Location = new System.Drawing.Point(164, 3);
            this.TxtExent.MaxLength = 9;
            this.TxtExent.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtExent.Modified = false;
            this.TxtExent.Multiline = false;
            this.TxtExent.Name = "TxtExent";
            stateProperties69.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties69.FillColor = System.Drawing.Color.Empty;
            stateProperties69.ForeColor = System.Drawing.Color.Empty;
            stateProperties69.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtExent.OnActiveState = stateProperties69;
            stateProperties70.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties70.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties70.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties70.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtExent.OnDisabledState = stateProperties70;
            stateProperties71.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties71.FillColor = System.Drawing.Color.Empty;
            stateProperties71.ForeColor = System.Drawing.Color.Empty;
            stateProperties71.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtExent.OnHoverState = stateProperties71;
            stateProperties72.BorderColor = System.Drawing.Color.Silver;
            stateProperties72.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            stateProperties72.ForeColor = System.Drawing.Color.Empty;
            stateProperties72.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtExent.OnIdleState = stateProperties72;
            this.TxtExent.Padding = new System.Windows.Forms.Padding(3);
            this.TxtExent.PasswordChar = '\0';
            this.TxtExent.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtExent.PlaceholderText = "$ Exent";
            this.TxtExent.ReadOnly = true;
            this.TxtExent.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtExent.SelectedText = "";
            this.TxtExent.SelectionLength = 0;
            this.TxtExent.SelectionStart = 0;
            this.TxtExent.ShortcutsEnabled = true;
            this.TxtExent.Size = new System.Drawing.Size(103, 25);
            this.TxtExent.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtExent.TabIndex = 28;
            this.TxtExent.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtExent.TextMarginBottom = 0;
            this.TxtExent.TextMarginLeft = 1;
            this.TxtExent.TextMarginTop = 0;
            this.TxtExent.TextPlaceholder = "$ Exent";
            this.TxtExent.UseSystemPasswordChar = false;
            this.TxtExent.WordWrap = true;
            // 
            // TxtGlosa
            // 
            this.TxtGlosa.AcceptsReturn = false;
            this.TxtGlosa.AcceptsTab = false;
            this.TxtGlosa.AnimationSpeed = 200;
            this.TxtGlosa.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtGlosa.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtGlosa.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            this.TxtGlosa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtGlosa.BackgroundImage")));
            this.TxtGlosa.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtGlosa.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtGlosa.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtGlosa.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtGlosa.BorderRadius = 1;
            this.TxtGlosa.BorderThickness = 1;
            this.TxtGlosa.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtGlosa.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtGlosa.DefaultFont = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TxtGlosa.DefaultText = "";
            this.TxtGlosa.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            this.TxtGlosa.HideSelection = true;
            this.TxtGlosa.IconLeft = null;
            this.TxtGlosa.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtGlosa.IconPadding = 10;
            this.TxtGlosa.IconRight = null;
            this.TxtGlosa.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtGlosa.Lines = new string[0];
            this.TxtGlosa.Location = new System.Drawing.Point(9, 130);
            this.TxtGlosa.MaxLength = 100;
            this.TxtGlosa.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtGlosa.Modified = false;
            this.TxtGlosa.Multiline = false;
            this.TxtGlosa.Name = "TxtGlosa";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtGlosa.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtGlosa.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtGlosa.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(106)))), ((int)(((byte)(112)))));
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtGlosa.OnIdleState = stateProperties40;
            this.TxtGlosa.Padding = new System.Windows.Forms.Padding(3);
            this.TxtGlosa.PasswordChar = '\0';
            this.TxtGlosa.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtGlosa.PlaceholderText = "Enter Resumen Purchase Requisition";
            this.TxtGlosa.ReadOnly = false;
            this.TxtGlosa.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtGlosa.SelectedText = "";
            this.TxtGlosa.SelectionLength = 0;
            this.TxtGlosa.SelectionStart = 0;
            this.TxtGlosa.ShortcutsEnabled = true;
            this.TxtGlosa.Size = new System.Drawing.Size(525, 25);
            this.TxtGlosa.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtGlosa.TabIndex = 31;
            this.TxtGlosa.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtGlosa.TextMarginBottom = 0;
            this.TxtGlosa.TextMarginLeft = 1;
            this.TxtGlosa.TextMarginTop = 0;
            this.TxtGlosa.TextPlaceholder = "Enter Resumen Purchase Requisition";
            this.TxtGlosa.UseSystemPasswordChar = false;
            this.TxtGlosa.WordWrap = true;
            this.TxtGlosa.Leave += new System.EventHandler(this.TxtGlosa_Leave);
            // 
            // ChkExent
            // 
            this.ChkExent.AllowBindingControlAnimation = true;
            this.ChkExent.AllowBindingControlColorChanges = false;
            this.ChkExent.AllowBindingControlLocation = true;
            this.ChkExent.AllowCheckBoxAnimation = false;
            this.ChkExent.AllowCheckmarkAnimation = true;
            this.ChkExent.AllowOnHoverStates = true;
            this.ChkExent.AutoCheck = true;
            this.ChkExent.BackColor = System.Drawing.Color.Transparent;
            this.ChkExent.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ChkExent.BackgroundImage")));
            this.ChkExent.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.ChkExent.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.ChkExent.BorderRadius = 12;
            this.ChkExent.Checked = false;
            this.ChkExent.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Unchecked;
            this.ChkExent.Cursor = System.Windows.Forms.Cursors.Default;
            this.ChkExent.CustomCheckmarkImage = null;
            this.ChkExent.Location = new System.Drawing.Point(432, 97);
            this.ChkExent.MinimumSize = new System.Drawing.Size(17, 17);
            this.ChkExent.Name = "ChkExent";
            this.ChkExent.OnCheck.BorderColor = System.Drawing.Color.DodgerBlue;
            this.ChkExent.OnCheck.BorderRadius = 12;
            this.ChkExent.OnCheck.BorderThickness = 2;
            this.ChkExent.OnCheck.CheckBoxColor = System.Drawing.Color.DodgerBlue;
            this.ChkExent.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.ChkExent.OnCheck.CheckmarkThickness = 2;
            this.ChkExent.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.ChkExent.OnDisable.BorderRadius = 12;
            this.ChkExent.OnDisable.BorderThickness = 2;
            this.ChkExent.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.ChkExent.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.ChkExent.OnDisable.CheckmarkThickness = 2;
            this.ChkExent.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ChkExent.OnHoverChecked.BorderRadius = 12;
            this.ChkExent.OnHoverChecked.BorderThickness = 2;
            this.ChkExent.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ChkExent.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.ChkExent.OnHoverChecked.CheckmarkThickness = 2;
            this.ChkExent.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ChkExent.OnHoverUnchecked.BorderRadius = 12;
            this.ChkExent.OnHoverUnchecked.BorderThickness = 1;
            this.ChkExent.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.ChkExent.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.ChkExent.OnUncheck.BorderRadius = 12;
            this.ChkExent.OnUncheck.BorderThickness = 1;
            this.ChkExent.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.ChkExent.Size = new System.Drawing.Size(21, 21);
            this.ChkExent.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.ChkExent.TabIndex = 32;
            this.ChkExent.ThreeState = false;
            this.ChkExent.ToolTipText = null;
            // 
            // FDetails
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(37)))), ((int)(((byte)(38)))));
            this.ClientSize = new System.Drawing.Size(546, 354);
            this.Controls.Add(this.ChkExent);
            this.Controls.Add(this.TxtGlosa);
            this.Controls.Add(this.Grid);
            this.Controls.Add(this.PanelFooter);
            this.Controls.Add(this.CboMedidas);
            this.Controls.Add(this.bunifuSeparator2);
            this.Controls.Add(this.BtnNewDetail);
            this.Controls.Add(this.bunifuSeparator1);
            this.Controls.Add(this.TxtPrice);
            this.Controls.Add(this.TxtDescription);
            this.Controls.Add(this.CboAccount);
            this.Controls.Add(this.TxtQty);
            this.Controls.Add(this.TxtName);
            this.Controls.Add(this.PanelHeader);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FDetails";
            this.Text = "FOrderDetail";
            this.Load += new System.EventHandler(this.FDetails_Load);
            this.PanelHeader.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.Grid)).EndInit();
            this.PanelFooter.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel PanelHeader;
        private Bunifu.UI.WinForms.BunifuFormDock FDock;
        private TenTec.Windows.iGridLib.iGrid Grid;
        private Bunifu.UI.WinForms.BunifuTextBox TxtPrice;
        private Bunifu.UI.WinForms.BunifuTextBox TxtDescription;
        private System.Windows.Forms.ComboBox CboAccount;
        private Bunifu.UI.WinForms.BunifuTextBox TxtQty;
        private Bunifu.UI.WinForms.BunifuTextBox TxtName;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
        private Bunifu.UI.WinForms.BunifuImageButton BtnNewDetail;
        private Bunifu.UI.WinForms.BunifuImageButton BtnCerrar;
        private System.Windows.Forms.Label LabelPanel;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator2;
        private System.Windows.Forms.Panel PanelFooter;
        private System.Windows.Forms.ComboBox CboMedidas;
        private Bunifu.UI.WinForms.BunifuTextBox TxtNet;
        private Bunifu.UI.WinForms.BunifuTextBox TxtExent;
        private Bunifu.UI.WinForms.BunifuTextBox TxtTotal;
        private Bunifu.UI.WinForms.BunifuTextBox TxtTax;
        private Bunifu.UI.WinForms.BunifuTextBox TxtGlosa;
        private Bunifu.UI.WinForms.BunifuCheckBox ChkExent;
    }
}