//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseData.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigApp
    {
        public int ConfigID { get; set; }
        public string ApikeySBIF { get; set; }
        public string BaseSBIF { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string FolderApp { get; set; }
        public string AddressCompany { get; set; }
        public string GiroCompany { get; set; }
        public string PhoneCompany { get; set; }
        public string Comentarios { get; set; }
        public int Year { get; set; }
    }
}
