//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseData.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PurchaseManagerContext : DbContext
    {
        public PurchaseManagerContext()
            : base("name=PurchaseManagerContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Attaches> Attaches { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Currencies> Currencies { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<OrderHeader> OrderHeader { get; set; }
        public virtual DbSet<OrderHitos> OrderHitos { get; set; }
        public virtual DbSet<OrderNotes> OrderNotes { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
        public virtual DbSet<RequisitionDetails> RequisitionDetails { get; set; }
        public virtual DbSet<RequisitionHeader> RequisitionHeader { get; set; }
        public virtual DbSet<RequisitionStatus> RequisitionStatus { get; set; }
        public virtual DbSet<SupplierBanks> SupplierBanks { get; set; }
        public virtual DbSet<SupplierCountries> SupplierCountries { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
        public virtual DbSet<UserCosts> UserCosts { get; set; }
        public virtual DbSet<UserProfiles> UserProfiles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<vOrderByMinTransaction> vOrderByMinTransaction { get; set; }
        public virtual DbSet<vRequisitionByMinTransaction> vRequisitionByMinTransaction { get; set; }
    
        [DbFunction("PurchaseManagerContext", "ufnGetReqGroupByCost")]
        public virtual IQueryable<ufnGetReqGroupByCost_Result> ufnGetReqGroupByCost(Nullable<int> statusID)
        {
            var statusIDParameter = statusID.HasValue ?
                new ObjectParameter("StatusID", statusID) :
                new ObjectParameter("StatusID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufnGetReqGroupByCost_Result>("[PurchaseManagerContext].[ufnGetReqGroupByCost](@StatusID)", statusIDParameter);
        }
    
        [DbFunction("PurchaseManagerContext", "ufnGetOrderGroupByStatus")]
        public virtual IQueryable<ufnGetOrderGroupByStatus_Result> ufnGetOrderGroupByStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufnGetOrderGroupByStatus_Result>("[PurchaseManagerContext].[ufnGetOrderGroupByStatus]()");
        }
    
        [DbFunction("PurchaseManagerContext", "ufnGetOrderGroupByStatus1")]
        public virtual IQueryable<ufnGetOrderGroupByStatus1_Result> ufnGetOrderGroupByStatus1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufnGetOrderGroupByStatus1_Result>("[PurchaseManagerContext].[ufnGetOrderGroupByStatus1]()");
        }
    
        [DbFunction("PurchaseManagerContext", "ufnGetReqGroupByCost1")]
        public virtual IQueryable<ufnGetReqGroupByCost1_Result> ufnGetReqGroupByCost1(Nullable<int> statusID)
        {
            var statusIDParameter = statusID.HasValue ?
                new ObjectParameter("StatusID", statusID) :
                new ObjectParameter("StatusID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufnGetReqGroupByCost1_Result>("[PurchaseManagerContext].[ufnGetReqGroupByCost1](@StatusID)", statusIDParameter);
        }
    }
}
