//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseData.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PurchaseManagerContext : DbContext
    {
        public PurchaseManagerContext()
            : base("name=PurchaseManagerContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OrderAccounts> OrderAccounts { get; set; }
        public virtual DbSet<OrderAttaches> OrderAttaches { get; set; }
        public virtual DbSet<OrderCompanies> OrderCompanies { get; set; }
        public virtual DbSet<OrderCurrencies> OrderCurrencies { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<OrderHeader> OrderHeader { get; set; }
        public virtual DbSet<OrderHitos> OrderHitos { get; set; }
        public virtual DbSet<OrderNotes> OrderNotes { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
        public virtual DbSet<OrderTransactions> OrderTransactions { get; set; }
        public virtual DbSet<OrderUsers> OrderUsers { get; set; }
        public virtual DbSet<SupplierBanks> SupplierBanks { get; set; }
        public virtual DbSet<SupplierCountries> SupplierCountries { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserCosts> UserCosts { get; set; }
        public virtual DbSet<UserProfiles> UserProfiles { get; set; }
        public virtual DbSet<vOrderByMinTran> vOrderByMinTran { get; set; }
    }
}
