//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseData.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionDetails
    {
        public int DetailID { get; set; }
        public int RequisitionHeaderID { get; set; }
        public string NameProduct { get; set; }
        public string DescriptionProduct { get; set; }
        public int Qty { get; set; }
        public string AccountID { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual RequisitionHeader RequisitionHeader { get; set; }
    }
}
