//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseData.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOrderByMinTransaction
    {
        public int OrderHeaderID { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<decimal> Exent { get; set; }
        public decimal Tax { get; set; }
        public decimal Total { get; set; }
        public Nullable<byte> Type { get; set; }
        public byte StatusID { get; set; }
        public string UserID { get; set; }
        public string CostID { get; set; }
        public Nullable<System.DateTime> DateLast { get; set; }
        public string Event { get; set; }
        public string SupplierID { get; set; }
    }
}
